spring:
   datasource: 
      url: jdbc:mysql://localhost:3306/naprawagsm?useSSL=false&serverTimezone=Europe/Warsaw
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: Argentyna112
   jdbc: 
      show-sql: true
      hibernate:
         ddl-auto: update
   security:
      user:
         name: Kamil
         password: java2023