spring:
   datasource: 
      url: jdbc:mysql://mysql:3306/naprawagsm?useSSL=false&serverTimezone=Europe/Warsaw&allowPublicKeyRetrieval=true
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: Polska12345!
   jdbc: 
      show-sql: true
      hibernate:
         ddl-auto: none
   thymeleaf:
      encoding: UTF-8
   liquibase:
      contexts: prod